---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy
  labels:
    app: reverse-proxy
spec:
  selector:
    matchLabels:
      app: reverse-proxy
      release: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
        release: reverse-proxy
    spec:
      containers:
      - name: reverse-proxy
        image: "beelzebubabhi/reverse-proxy:latest"
        imagePullPolicy: IfNotPresent
        command: ["./reverse-proxy"]
        args: ["start", "--ipaddress", "172.200.18.22", "--port", "443", "--protocol", "https", "--proxyport", "5556", "--httptimeout", "10", "--certfile", "cert.crt", "--keyfile", "key.key", "--insecure", "true"]
        ports:
        - name: http
          containerPort: 5556
          protocol: TCP
        resources:
          limits:
            cpu: 50m
            memory: 32Mi
          requests:
            cpu: 50m
            memory: 32Mi
