---
apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy
  labels:
    app: reverse-proxy
spec:
  loadBalancerIP: ""
  type: LoadBalancer
  ports:
    - port: 5556
      targetPort: 5556
      protocol: TCP
      name: http
  selector:
    app: reverse-proxy
    release: reverse-proxy
